services:
  - type: web
    name: easyrti-backend
    rootDir: backend # Specify the backend directory
    runtime: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: MONGO_URL
        value: "mongodb+srv://feroz:feroz2222@easyrti.b29fu.mongodb.net/easyrti"
      - key: PORT
        value: 8053
      - key: CLOUD_NAME
        value: dmf0l0i74
      - key: CLOUD_API_KEY
        value: 224969239394187
      - key: CLOUD_API_SECRET
        value: ACX13ORG7lFKuJ4Kqy09oyXZCts
      - key: SECRET_KEY
        value: bsdbsjndbcnsbncsndbcnb
      - key: JWT_SECRET
        value: ada48f6aac3f701ed9342246bc72471094fa3418dfb3de73d27d2623c25875498b25ed37be98ac586aeb8d6b35f10226947a2a990b294533e17da0e72c8de59b
      - key: JWT_EXPIRES_IN
        value: 43200
      - key: FRONTEND_URL
        value: "https://easyrti-frontend.onrender.com"

  - type: web
    name: easyrti-frontend
    rootDir: frontend # Specify the frontend directory
    buildCommand: "npm install && npm run build"
    envVars:
        - key: VITE_BACKEND_API_URL
  
  - type: web
    name: easyrti-model
    rootDir: backend # Update to the backend directory where the model resides
    runtime: python
    buildCommand: "pip install -r requirements.txt" # Install dependencies
    startCommand: "uvicorn bert_model:app --host 0.0.0.0 --port 8000" # Start FastAPI app
    # Removed the memory property as it is not allowed